version: "3"

# This file is used when testing the application with docker-compose.
# Build and run with 'docker-compose build && docker-compose up'.

services:
  nsv-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      - cluster.name=nsv-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - nsv-es-data:/usr/share/elasticsearch/data
    ports:
      # This can be changed to just "9200" if external access to
      # elasticsearch is not needed.
      - "9200:9200"

  # This only uploads initial data and can be excluded.
  nsv-initial-data-uploader:
    build: ./initial-data-uploader
    links:
      - nsv-es
    depends_on:
      - nsv-es

  nsv-backend:
    build: ./backend
    links:
      - nsv-es
    depends_on:
      - nsv-es
    ports:
      - "5001:5001"

  nsv-frontend:
    build: ./frontend
    links:
      - nsv-backend
    depends_on:
      - nsv-backend
    environment:
      # This is where the server name should be changed.
      # There's no need to create a custom image on every deployment.
      - NSV_FRONTEND_SERVERNAME=localhost
      # This will show some messages at startup.
      - NSV_FRONTEND_DEBUG=true
    ports:
      - "80:80"

volumes:
  nsv-es-data:
